-- =============================================================================
-- MULTI-AGENT RBAC DEMO - Complete Setup Script
-- =============================================================================
-- This demo shows how Cortex Agents respect row-level security policies.
-- An orchestrator agent routes queries to specialized sub-agents, and each
-- user sees only the data their role permits.
-- =============================================================================

-- =============================================
-- PART 1: DATABASE AND SCHEMA SETUP
-- =============================================

CREATE DATABASE IF NOT EXISTS MULTI_AGENT_RBAC_DEMO;

CREATE SCHEMA IF NOT EXISTS MULTI_AGENT_RBAC_DEMO.SALES;
CREATE SCHEMA IF NOT EXISTS MULTI_AGENT_RBAC_DEMO.FINANCE;
CREATE SCHEMA IF NOT EXISTS MULTI_AGENT_RBAC_DEMO.HR;
CREATE SCHEMA IF NOT EXISTS MULTI_AGENT_RBAC_DEMO.AGENTS;
CREATE SCHEMA IF NOT EXISTS MULTI_AGENT_RBAC_DEMO.TOOLS;

-- =============================================
-- PART 2: ROLE SETUP
-- =============================================

-- Create demo roles
CREATE ROLE IF NOT EXISTS SALES_WEST_ROLE;
CREATE ROLE IF NOT EXISTS SALES_EAST_ROLE;
CREATE ROLE IF NOT EXISTS SALES_MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS FINANCE_ANALYST_ROLE;
CREATE ROLE IF NOT EXISTS HR_ROLE;
CREATE ROLE IF NOT EXISTS EXECUTIVE_ROLE;

-- Grant roles to SYSADMIN for hierarchy
GRANT ROLE SALES_WEST_ROLE TO ROLE SYSADMIN;
GRANT ROLE SALES_EAST_ROLE TO ROLE SYSADMIN;
GRANT ROLE SALES_MANAGER_ROLE TO ROLE SYSADMIN;
GRANT ROLE FINANCE_ANALYST_ROLE TO ROLE SYSADMIN;
GRANT ROLE HR_ROLE TO ROLE SYSADMIN;
GRANT ROLE EXECUTIVE_ROLE TO ROLE SYSADMIN;

-- =============================================
-- PART 3: USER SETUP (Optional - create demo users)
-- =============================================

-- Create demo users (uncomment if needed)
-- CREATE USER IF NOT EXISTS SALES_REP_WEST PASSWORD = 'TempPassword123!' DEFAULT_ROLE = SALES_WEST_ROLE;
-- CREATE USER IF NOT EXISTS SALES_REP_EAST PASSWORD = 'TempPassword123!' DEFAULT_ROLE = SALES_EAST_ROLE;
-- CREATE USER IF NOT EXISTS SALES_MANAGER_USER PASSWORD = 'TempPassword123!' DEFAULT_ROLE = SALES_MANAGER_ROLE;
-- CREATE USER IF NOT EXISTS FINANCE_ANALYST_USER PASSWORD = 'TempPassword123!' DEFAULT_ROLE = FINANCE_ANALYST_ROLE;
-- CREATE USER IF NOT EXISTS HR_REP_USER PASSWORD = 'TempPassword123!' DEFAULT_ROLE = HR_ROLE;
-- CREATE USER IF NOT EXISTS EXECUTIVE_USER PASSWORD = 'TempPassword123!' DEFAULT_ROLE = EXECUTIVE_ROLE;

-- Grant roles to users
-- GRANT ROLE SALES_WEST_ROLE TO USER SALES_REP_WEST;
-- GRANT ROLE SALES_EAST_ROLE TO USER SALES_REP_EAST;
-- GRANT ROLE SALES_MANAGER_ROLE TO USER SALES_MANAGER_USER;
-- GRANT ROLE FINANCE_ANALYST_ROLE TO USER FINANCE_ANALYST_USER;
-- GRANT ROLE HR_ROLE TO USER HR_REP_USER;
-- GRANT ROLE EXECUTIVE_ROLE TO USER EXECUTIVE_USER;

-- =============================================
-- PART 4: ROW ACCESS POLICIES
-- =============================================

-- Sales Region Policy
CREATE OR REPLACE ROW ACCESS POLICY MULTI_AGENT_RBAC_DEMO.SALES.SALES_REGION_POLICY 
AS (REGION VARCHAR) 
RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_MANAGER_ROLE') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_WEST_ROLE') AND region = 'WEST' THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_EAST_ROLE') AND region = 'EAST' THEN TRUE
        ELSE FALSE
    END;

-- Finance Budget Policy
CREATE OR REPLACE ROW ACCESS POLICY MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET_DEPT_POLICY 
AS (DEPARTMENT VARCHAR) 
RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('FINANCE_ANALYST_ROLE') AND department != 'EXECUTIVE' THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_MANAGER_ROLE') AND department = 'SALES' THEN TRUE
        WHEN IS_ROLE_IN_SESSION('HR_ROLE') AND department = 'HR' THEN TRUE
        ELSE FALSE
    END;

-- HR Employee Policy
CREATE OR REPLACE ROW ACCESS POLICY MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEE_ACCESS_POLICY 
AS (DEPARTMENT VARCHAR, REGION VARCHAR) 
RETURNS BOOLEAN ->
    CASE
        WHEN IS_ROLE_IN_SESSION('EXECUTIVE_ROLE') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('ACCOUNTADMIN') THEN TRUE
        WHEN IS_ROLE_IN_SESSION('HR_ROLE') AND department != 'EXECUTIVE' THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_MANAGER_ROLE') AND department = 'SALES' THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_WEST_ROLE') AND region = 'WEST' THEN TRUE
        WHEN IS_ROLE_IN_SESSION('SALES_EAST_ROLE') AND region = 'EAST' THEN TRUE
        ELSE FALSE
    END;

-- =============================================
-- PART 5: TABLE CREATION WITH POLICIES
-- =============================================

-- Sales Opportunities Table
CREATE OR REPLACE TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES (
    OPPORTUNITY_ID NUMBER(38,0),
    ACCOUNT_NAME VARCHAR(16777216),
    DEAL_VALUE NUMBER(12,2),
    STAGE VARCHAR(16777216),
    REGION VARCHAR(16777216),
    SALES_REP VARCHAR(16777216),
    CLOSE_DATE DATE,
    PRODUCT VARCHAR(16777216)
) WITH ROW ACCESS POLICY MULTI_AGENT_RBAC_DEMO.SALES.SALES_REGION_POLICY ON (REGION);

-- Finance Budget Table
CREATE OR REPLACE TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET (
    BUDGET_ID NUMBER(38,0),
    DEPARTMENT VARCHAR(16777216),
    CATEGORY VARCHAR(16777216),
    ALLOCATED_AMOUNT NUMBER(12,2),
    SPENT_AMOUNT NUMBER(12,2),
    FISCAL_YEAR NUMBER(38,0),
    QUARTER VARCHAR(16777216)
) WITH ROW ACCESS POLICY MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET_DEPT_POLICY ON (DEPARTMENT);

-- HR Employees Table
CREATE OR REPLACE TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES (
    EMPLOYEE_ID NUMBER(38,0),
    NAME VARCHAR(16777216),
    TITLE VARCHAR(16777216),
    DEPARTMENT VARCHAR(16777216),
    REGION VARCHAR(16777216),
    HIRE_DATE DATE,
    SALARY NUMBER(12,2)
) WITH ROW ACCESS POLICY MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEE_ACCESS_POLICY ON (DEPARTMENT, REGION);

-- =============================================
-- PART 6: SAMPLE DATA
-- =============================================

-- Sales Opportunities Data
INSERT INTO MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES VALUES
    (1001, 'Acme Corp', 150000.00, 'Closed Won', 'WEST', 'Alice Johnson', '2025-01-15', 'Enterprise Platform'),
    (1002, 'TechStart Inc', 75000.00, 'Negotiation', 'WEST', 'Alice Johnson', '2025-02-28', 'Data Analytics'),
    (1003, 'Pacific Solutions', 200000.00, 'Closed Won', 'WEST', 'Bob Smith', '2025-01-20', 'Enterprise Platform'),
    (1004, 'Golden Gate Ltd', 50000.00, 'Proposal', 'WEST', 'Alice Johnson', '2025-03-15', 'Cloud Storage'),
    (1005, 'Silicon Dynamics', 300000.00, 'Closed Won', 'WEST', 'Bob Smith', '2025-02-01', 'AI Suite'),
    (1006, 'Atlantic Industries', 450000.00, 'Closed Won', 'EAST', 'Carol Davis', '2025-01-10', 'Enterprise Platform'),
    (1007, 'Metro Systems', 180000.00, 'Negotiation', 'EAST', 'Dan Wilson', '2025-03-01', 'Data Analytics'),
    (1008, 'Eastern Digital', 350000.00, 'Closed Won', 'EAST', 'Carol Davis', '2025-02-15', 'AI Suite'),
    (1009, 'Harbor Tech', 120000.00, 'Proposal', 'EAST', 'Dan Wilson', '2025-04-01', 'Cloud Storage'),
    (1010, 'Coastal Innovations', 350000.00, 'Closed Won', 'EAST', 'Carol Davis', '2025-01-25', 'Enterprise Platform'),
    (1011, 'Midwest Manufacturing', 280000.00, 'Closed Won', 'CENTRAL', 'Eve Martinez', '2025-02-10', 'AI Suite'),
    (1012, 'Plains Energy Co', 200000.00, 'Negotiation', 'CENTRAL', 'Frank Brown', '2025-03-20', 'Data Analytics'),
    (1013, 'Heartland Services', 150000.00, 'Closed Won', 'CENTRAL', 'Eve Martinez', '2025-01-30', 'Enterprise Platform'),
    (1014, 'Central Logistics', 250000.00, 'Proposal', 'CENTRAL', 'Frank Brown', '2025-04-15', 'Cloud Storage'),
    (1015, 'Great Lakes Tech', 150000.00, 'Closed Won', 'CENTRAL', 'Eve Martinez', '2025-02-20', 'Data Analytics');

-- Finance Budget Data
INSERT INTO MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET VALUES
    (1, 'SALES', 'Marketing', 200000.00, 180000.00, 2025, 'Q1'),
    (2, 'SALES', 'Travel', 150000.00, 120000.00, 2025, 'Q1'),
    (3, 'SALES', 'Training', 100000.00, 90000.00, 2025, 'Q1'),
    (4, 'SALES', 'Events', 100000.00, 90000.00, 2025, 'Q1'),
    (5, 'ENGINEERING', 'Cloud Infrastructure', 500000.00, 450000.00, 2025, 'Q1'),
    (6, 'ENGINEERING', 'Software Licenses', 300000.00, 280000.00, 2025, 'Q1'),
    (7, 'ENGINEERING', 'R&D', 400000.00, 350000.00, 2025, 'Q1'),
    (8, 'ENGINEERING', 'Equipment', 250000.00, 125000.00, 2025, 'Q1'),
    (9, 'HR', 'Recruiting', 300000.00, 250000.00, 2025, 'Q1'),
    (10, 'HR', 'Benefits Administration', 200000.00, 180000.00, 2025, 'Q1'),
    (11, 'HR', 'Training Programs', 275000.00, 240000.00, 2025, 'Q1'),
    (12, 'EXECUTIVE', 'Strategic Initiatives', 2000000.00, 500000.00, 2025, 'Q1'),
    (13, 'EXECUTIVE', 'M&A Reserve', 1000000.00, 150000.00, 2025, 'Q1'),
    (14, 'EXECUTIVE', 'Board Operations', 250000.00, 50000.00, 2025, 'Q1');

-- HR Employees Data
INSERT INTO MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES VALUES
    (1, 'Alice Johnson', 'Sales Rep', 'SALES', 'WEST', '2022-03-15', 120000.00),
    (2, 'Bob Smith', 'Sales Rep', 'SALES', 'WEST', '2021-06-01', 115000.00),
    (3, 'Carol Davis', 'Sr Sales Rep', 'SALES', 'EAST', '2020-02-01', 140000.00),
    (4, 'Dan Wilson', 'Sales Rep', 'SALES', 'EAST', '2023-04-15', 110000.00),
    (5, 'Eve Martinez', 'Sales Rep', 'SALES', 'CENTRAL', '2021-09-15', 118000.00),
    (6, 'Frank Brown', 'Sales Manager', 'SALES', 'CENTRAL', '2018-05-01', 160000.00),
    (7, 'Grace Lee', 'Software Engineer', 'ENGINEERING', 'WEST', '2023-01-10', 145000.00),
    (8, 'Henry Chen', 'Data Scientist', 'ENGINEERING', 'WEST', '2022-08-20', 155000.00),
    (9, 'Ivy Zhang', 'Sr Engineer', 'ENGINEERING', 'EAST', '2019-11-01', 165000.00),
    (10, 'Jack Brown', 'Engineer', 'ENGINEERING', 'EAST', '2022-07-01', 135000.00),
    (11, 'Kim Park', 'Engineering Manager', 'ENGINEERING', 'CENTRAL', '2017-03-01', 180000.00),
    (12, 'Leo Garcia', 'HR Specialist', 'HR', 'CENTRAL', '2022-01-15', 95000.00),
    (13, 'Maria Santos', 'HR Manager', 'HR', 'CENTRAL', '2019-06-01', 130000.00),
    (14, 'Nancy White', 'CEO', 'EXECUTIVE', 'HQ', '2015-01-01', 450000.00),
    (15, 'Oscar Black', 'CFO', 'EXECUTIVE', 'HQ', '2016-03-01', 380000.00),
    (16, 'Paula Green', 'CTO', 'EXECUTIVE', 'HQ', '2016-06-01', 400000.00);

-- =============================================
-- PART 7: STORED PROCEDURES (Tools for Agents)
-- =============================================

-- CALL_SALES_AGENT - Calls Sales Agent via DATA_AGENT_RUN
CREATE OR REPLACE PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(QUERY VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    full_result STRING;
    text_result STRING;
    request_json STRING;
    thread_id STRING;
BEGIN
    thread_id := UUID_STRING();
    
    SELECT OBJECT_CONSTRUCT(
        'threadId', :thread_id,
        'messages', ARRAY_CONSTRUCT(
            OBJECT_CONSTRUCT(
                'role', 'user',
                'content', ARRAY_CONSTRUCT(
                    OBJECT_CONSTRUCT('type', 'text', 'text', :query)
                )
            )
        )
    )::STRING INTO :request_json;
    
    SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
        'MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT',
        :request_json
    ) INTO :full_result;
    
    SELECT LISTAGG(value:text::STRING, '') WITHIN GROUP (ORDER BY index)
    INTO :text_result
    FROM TABLE(FLATTEN(INPUT => PARSE_JSON(:full_result):content))
    WHERE value:type = 'text';
    
    RETURN COALESCE(NULLIF(:text_result, ''), :full_result);
EXCEPTION
    WHEN OTHER THEN
        RETURN 'ERROR: ' || SQLERRM || ' | SQLCODE: ' || SQLCODE;
END;
$$;

-- CALL_FINANCE_AGENT - Calls Finance Agent via DATA_AGENT_RUN
CREATE OR REPLACE PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(QUERY VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    full_result STRING;
    text_result STRING;
    request_json STRING;
    thread_id STRING;
BEGIN
    thread_id := UUID_STRING();
    
    SELECT OBJECT_CONSTRUCT(
        'threadId', :thread_id,
        'messages', ARRAY_CONSTRUCT(
            OBJECT_CONSTRUCT(
                'role', 'user',
                'content', ARRAY_CONSTRUCT(
                    OBJECT_CONSTRUCT('type', 'text', 'text', :query)
                )
            )
        )
    )::STRING INTO :request_json;
    
    SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
        'MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT',
        :request_json
    ) INTO :full_result;
    
    SELECT LISTAGG(value:text::STRING, '') WITHIN GROUP (ORDER BY index)
    INTO :text_result
    FROM TABLE(FLATTEN(INPUT => PARSE_JSON(:full_result):content))
    WHERE value:type = 'text';
    
    RETURN COALESCE(NULLIF(:text_result, ''), :full_result);
EXCEPTION
    WHEN OTHER THEN
        RETURN 'ERROR: ' || SQLERRM || ' | SQLCODE: ' || SQLCODE;
END;
$$;

-- CALL_HR_AGENT - Calls HR Agent via DATA_AGENT_RUN
CREATE OR REPLACE PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(QUERY VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    full_result STRING;
    text_result STRING;
    request_json STRING;
    thread_id STRING;
BEGIN
    thread_id := UUID_STRING();
    
    SELECT OBJECT_CONSTRUCT(
        'threadId', :thread_id,
        'messages', ARRAY_CONSTRUCT(
            OBJECT_CONSTRUCT(
                'role', 'user',
                'content', ARRAY_CONSTRUCT(
                    OBJECT_CONSTRUCT('type', 'text', 'text', :query)
                )
            )
        )
    )::STRING INTO :request_json;
    
    SELECT SNOWFLAKE.CORTEX.DATA_AGENT_RUN(
        'MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT',
        :request_json
    ) INTO :full_result;
    
    SELECT LISTAGG(value:text::STRING, '') WITHIN GROUP (ORDER BY index)
    INTO :text_result
    FROM TABLE(FLATTEN(INPUT => PARSE_JSON(:full_result):content))
    WHERE value:type = 'text';
    
    RETURN COALESCE(NULLIF(:text_result, ''), :full_result);
EXCEPTION
    WHEN OTHER THEN
        RETURN 'ERROR: ' || SQLERRM || ' | SQLCODE: ' || SQLCODE;
END;
$$;

-- =============================================
-- PART 8: GRANTS - Database, Schema, Warehouse
-- =============================================

-- Grant warehouse usage (adjust warehouse name as needed)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HR_ROLE;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE EXECUTIVE_ROLE;

-- Grant database usage
GRANT USAGE ON DATABASE MULTI_AGENT_RBAC_DEMO TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON DATABASE MULTI_AGENT_RBAC_DEMO TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON DATABASE MULTI_AGENT_RBAC_DEMO TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON DATABASE MULTI_AGENT_RBAC_DEMO TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON DATABASE MULTI_AGENT_RBAC_DEMO TO ROLE HR_ROLE;
GRANT USAGE ON DATABASE MULTI_AGENT_RBAC_DEMO TO ROLE EXECUTIVE_ROLE;

-- Grant schema usage
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.SALES TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.SALES TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.SALES TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.SALES TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.SALES TO ROLE HR_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.SALES TO ROLE EXECUTIVE_ROLE;

GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.FINANCE TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.FINANCE TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.FINANCE TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.FINANCE TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.FINANCE TO ROLE HR_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.FINANCE TO ROLE EXECUTIVE_ROLE;

GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.HR TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.HR TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.HR TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.HR TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.HR TO ROLE HR_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.HR TO ROLE EXECUTIVE_ROLE;

GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.AGENTS TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.AGENTS TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.AGENTS TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.AGENTS TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.AGENTS TO ROLE HR_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.AGENTS TO ROLE EXECUTIVE_ROLE;

GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.TOOLS TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.TOOLS TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.TOOLS TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.TOOLS TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.TOOLS TO ROLE HR_ROLE;
GRANT USAGE ON SCHEMA MULTI_AGENT_RBAC_DEMO.TOOLS TO ROLE EXECUTIVE_ROLE;

-- =============================================
-- PART 9: GRANTS - Tables (Row policies apply automatically)
-- =============================================

GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES TO ROLE SALES_WEST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES TO ROLE SALES_EAST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES TO ROLE SALES_MANAGER_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES TO ROLE FINANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES TO ROLE HR_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES TO ROLE EXECUTIVE_ROLE;

GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET TO ROLE SALES_WEST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET TO ROLE SALES_EAST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET TO ROLE SALES_MANAGER_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET TO ROLE FINANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET TO ROLE HR_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.FINANCE.BUDGET TO ROLE EXECUTIVE_ROLE;

GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES TO ROLE SALES_WEST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES TO ROLE SALES_EAST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES TO ROLE SALES_MANAGER_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES TO ROLE FINANCE_ANALYST_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES TO ROLE HR_ROLE;
GRANT SELECT ON TABLE MULTI_AGENT_RBAC_DEMO.HR.EMPLOYEES TO ROLE EXECUTIVE_ROLE;

-- =============================================
-- PART 10: GRANTS - Stored Procedures
-- =============================================

GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(VARCHAR) TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(VARCHAR) TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(VARCHAR) TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(VARCHAR) TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(VARCHAR) TO ROLE HR_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT(VARCHAR) TO ROLE EXECUTIVE_ROLE;

GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(VARCHAR) TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(VARCHAR) TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(VARCHAR) TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(VARCHAR) TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(VARCHAR) TO ROLE HR_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT(VARCHAR) TO ROLE EXECUTIVE_ROLE;

GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(VARCHAR) TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(VARCHAR) TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(VARCHAR) TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(VARCHAR) TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(VARCHAR) TO ROLE HR_ROLE;
GRANT USAGE ON PROCEDURE MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT(VARCHAR) TO ROLE EXECUTIVE_ROLE;

-- =============================================
-- PART 11: GRANTS - Agents (Run AFTER creating agents in UI)
-- =============================================

-- NOTE: Create agents first in Snowsight UI (AI & ML -> Agents), then run these grants

-- ORCHESTRATOR_AGENT grants
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.ORCHESTRATOR_AGENT TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.ORCHESTRATOR_AGENT TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.ORCHESTRATOR_AGENT TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.ORCHESTRATOR_AGENT TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.ORCHESTRATOR_AGENT TO ROLE HR_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.ORCHESTRATOR_AGENT TO ROLE EXECUTIVE_ROLE;

-- SALES_AGENT grants
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT TO ROLE HR_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.SALES_AGENT TO ROLE EXECUTIVE_ROLE;

-- FINANCE_AGENT grants
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT TO ROLE HR_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.FINANCE_AGENT TO ROLE EXECUTIVE_ROLE;

-- HR_AGENT grants
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT TO ROLE SALES_WEST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT TO ROLE SALES_EAST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT TO ROLE SALES_MANAGER_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT TO ROLE FINANCE_ANALYST_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT TO ROLE HR_ROLE;
GRANT USAGE ON AGENT MULTI_AGENT_RBAC_DEMO.AGENTS.HR_AGENT TO ROLE EXECUTIVE_ROLE;

-- =============================================
-- PART 12: TESTING
-- =============================================

-- Test row-level access by switching roles
-- USE ROLE SALES_WEST_ROLE;
-- SELECT * FROM MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES;  -- Should only see WEST region

-- USE ROLE SALES_EAST_ROLE;
-- SELECT * FROM MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES;  -- Should only see EAST region

-- USE ROLE EXECUTIVE_ROLE;
-- SELECT * FROM MULTI_AGENT_RBAC_DEMO.SALES.OPPORTUNITIES;  -- Should see all regions

-- Test stored procedures
-- CALL MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_SALES_AGENT('show my top deals');
-- CALL MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_FINANCE_AGENT('show budget summary');
-- CALL MULTI_AGENT_RBAC_DEMO.TOOLS.CALL_HR_AGENT('how many employees?');
