/*
=============================================================================
O&G Upstream Ontology Demo - Layer 3 Generated Views
=============================================================================
Dynamic abstraction views that provide business-friendly access to
the Knowledge Graph data. These views flatten the VARIANT properties
and join related entities for easy querying.

Views included:
  - V_WELLS: Well entity view
  - V_FIELDS: Field entity view
  - V_PRODUCTION: Production period view
  - V_FACILITIES: Facility entity view
  - V_EQUIPMENT: Equipment entity view
  - V_WELL_PRODUCTION: Wells joined with production data
  - V_WELL_FIELD: Wells with parent field info
  - V_FIELD_PRODUCTION: Field-level aggregation
  - V_WELL_EQUIPMENT: Wells with equipment status
  - V_MONTHLY_WELL_RANKING: Production rankings
  - V_PRODUCTION_TREND: Decline analysis
  - V_SHUT_IN_WELLS: Shut-in wells
=============================================================================
*/

-- Layer 3: Generated View for WELLS
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELLS 
COMMENT = 'Ontology View: Wells entity with flattened properties'
AS
SELECT 
    n.NODE_ID AS WELL_ID,
    n.NODE_KEY AS API_NUMBER,
    n.NODE_NAME AS WELL_NAME,
    n.NODE_DESCRIPTION AS DESCRIPTION,
    n.NODE_PROPERTIES:well_status::VARCHAR AS WELL_STATUS,
    n.NODE_PROPERTIES:well_type::VARCHAR AS WELL_TYPE,
    n.NODE_PROPERTIES:spud_date::DATE AS SPUD_DATE,
    n.NODE_PROPERTIES:completion_date::DATE AS COMPLETION_DATE,
    n.NODE_PROPERTIES:latitude::NUMBER(10,6) AS LATITUDE,
    n.NODE_PROPERTIES:longitude::NUMBER(10,6) AS LONGITUDE,
    n.NODE_PROPERTIES:total_depth::NUMBER AS TOTAL_DEPTH_FT,
    n.NODE_PROPERTIES:operator::VARCHAR AS OPERATOR,
    n.IS_ACTIVE,
    n.CREATED_AT,
    n.UPDATED_AT
FROM OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_NODE n
WHERE n.NODE_TYPE = 'WELL';

-- Layer 3: Generated View for FIELDS
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_FIELDS 
COMMENT = 'Ontology View: Fields entity with flattened properties'
AS
SELECT 
    n.NODE_ID AS FIELD_ID,
    n.NODE_KEY AS FIELD_CODE,
    n.NODE_NAME AS FIELD_NAME,
    n.NODE_DESCRIPTION AS DESCRIPTION,
    n.NODE_PROPERTIES:basin::VARCHAR AS BASIN,
    n.NODE_PROPERTIES:region::VARCHAR AS REGION,
    n.NODE_PROPERTIES:country::VARCHAR AS COUNTRY,
    n.NODE_PROPERTIES:discovery_date::DATE AS DISCOVERY_DATE,
    n.NODE_PROPERTIES:total_area::NUMBER AS TOTAL_AREA_ACRES,
    n.NODE_PROPERTIES:estimated_reserves_oil::NUMBER AS ESTIMATED_OIL_RESERVES_MMBBL,
    n.NODE_PROPERTIES:estimated_reserves_gas::NUMBER AS ESTIMATED_GAS_RESERVES_BCF,
    n.IS_ACTIVE,
    n.CREATED_AT
FROM OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_NODE n
WHERE n.NODE_TYPE = 'FIELD';

-- Layer 3: Generated View for PRODUCTION
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_PRODUCTION 
COMMENT = 'Ontology View: Production periods with flattened properties'
AS
SELECT 
    n.NODE_ID AS PRODUCTION_ID,
    n.NODE_KEY AS PRODUCTION_KEY,
    n.NODE_NAME AS PRODUCTION_NAME,
    n.NODE_PROPERTIES:period_date::DATE AS PERIOD_DATE,
    n.NODE_PROPERTIES:oil_volume::NUMBER AS OIL_VOLUME_BBL,
    n.NODE_PROPERTIES:gas_volume::NUMBER AS GAS_VOLUME_MCF,
    n.NODE_PROPERTIES:water_volume::NUMBER AS WATER_VOLUME_BBL,
    n.NODE_PROPERTIES:days_on_production::NUMBER AS DAYS_ON_PRODUCTION,
    n.NODE_PROPERTIES:downtime_hours::NUMBER AS DOWNTIME_HOURS,
    n.NODE_PROPERTIES:uptime_percentage::NUMBER(5,2) AS UPTIME_PCT,
    n.NODE_PROPERTIES:choke_size::NUMBER AS CHOKE_SIZE_INCHES,
    n.NODE_PROPERTIES:tubing_pressure::NUMBER AS TUBING_PRESSURE_PSI,
    n.NODE_PROPERTIES:casing_pressure::NUMBER AS CASING_PRESSURE_PSI,
    n.IS_ACTIVE,
    n.CREATED_AT
FROM OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_NODE n
WHERE n.NODE_TYPE = 'PRODUCTION_PERIOD';

-- Layer 3: Generated View for FACILITIES
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_FACILITIES 
COMMENT = 'Ontology View: Facilities with flattened properties'
AS
SELECT 
    n.NODE_ID AS FACILITY_ID,
    n.NODE_KEY AS FACILITY_CODE,
    n.NODE_NAME AS FACILITY_NAME,
    n.NODE_DESCRIPTION AS DESCRIPTION,
    n.NODE_PROPERTIES:facility_type::VARCHAR AS FACILITY_TYPE,
    n.NODE_PROPERTIES:capacity::NUMBER AS CAPACITY_BBL_DAY,
    n.NODE_PROPERTIES:install_date::DATE AS INSTALL_DATE,
    n.NODE_PROPERTIES:status::VARCHAR AS STATUS,
    n.IS_ACTIVE,
    n.CREATED_AT
FROM OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_NODE n
WHERE n.NODE_TYPE = 'FACILITY';

-- Layer 3: Generated View for EQUIPMENT
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_EQUIPMENT 
COMMENT = 'Ontology View: Equipment with flattened properties'
AS
SELECT 
    n.NODE_ID AS EQUIPMENT_ID,
    n.NODE_KEY AS EQUIPMENT_CODE,
    n.NODE_NAME AS EQUIPMENT_NAME,
    n.NODE_DESCRIPTION AS DESCRIPTION,
    n.NODE_PROPERTIES:equipment_type::VARCHAR AS EQUIPMENT_TYPE,
    n.NODE_PROPERTIES:manufacturer::VARCHAR AS MANUFACTURER,
    n.NODE_PROPERTIES:model::VARCHAR AS MODEL,
    n.NODE_PROPERTIES:serial_number::VARCHAR AS SERIAL_NUMBER,
    n.NODE_PROPERTIES:install_date::DATE AS INSTALL_DATE,
    n.NODE_PROPERTIES:last_maintenance_date::DATE AS LAST_MAINTENANCE_DATE,
    n.NODE_PROPERTIES:status::VARCHAR AS STATUS,
    n.NODE_PROPERTIES:failure_date::DATE AS FAILURE_DATE,
    n.IS_ACTIVE,
    n.CREATED_AT
FROM OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_NODE n
WHERE n.NODE_TYPE = 'EQUIPMENT';

-- Layer 3: Joined View for WELL PRODUCTION
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_PRODUCTION 
COMMENT = 'Ontology View: Wells with their production data'
AS
SELECT 
    w.WELL_ID,
    w.API_NUMBER,
    w.WELL_NAME,
    w.WELL_STATUS,
    w.WELL_TYPE,
    w.OPERATOR,
    p.PRODUCTION_ID,
    p.PERIOD_DATE,
    p.OIL_VOLUME_BBL,
    p.GAS_VOLUME_MCF,
    p.WATER_VOLUME_BBL,
    p.DAYS_ON_PRODUCTION,
    p.DOWNTIME_HOURS,
    p.UPTIME_PCT,
    DATE_TRUNC('MONTH', p.PERIOD_DATE) AS PRODUCTION_MONTH,
    DATE_TRUNC('QUARTER', p.PERIOD_DATE) AS PRODUCTION_QUARTER,
    YEAR(p.PERIOD_DATE) AS PRODUCTION_YEAR
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELLS w
JOIN OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_EDGE e 
    ON w.WELL_ID = e.SOURCE_NODE_ID AND e.EDGE_TYPE = 'HAS_PRODUCTION'
JOIN OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_PRODUCTION p 
    ON e.TARGET_NODE_ID = p.PRODUCTION_ID;

-- Layer 3: Well-Field relationship view
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_FIELD 
COMMENT = 'Ontology View: Wells with their parent fields'
AS
SELECT 
    w.WELL_ID,
    w.API_NUMBER,
    w.WELL_NAME,
    w.WELL_STATUS,
    w.WELL_TYPE,
    w.OPERATOR,
    w.SPUD_DATE,
    w.COMPLETION_DATE,
    w.TOTAL_DEPTH_FT,
    f.FIELD_ID,
    f.FIELD_CODE,
    f.FIELD_NAME,
    f.BASIN,
    f.REGION
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELLS w
JOIN OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_EDGE e 
    ON w.WELL_ID = e.SOURCE_NODE_ID AND e.EDGE_TYPE = 'PART_OF_FIELD'
JOIN OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_FIELDS f 
    ON e.TARGET_NODE_ID = f.FIELD_ID;

-- Layer 3: Well Equipment View
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_EQUIPMENT 
COMMENT = 'Ontology View: Wells with their equipment'
AS
SELECT 
    w.WELL_ID,
    w.API_NUMBER,
    w.WELL_NAME,
    w.WELL_STATUS,
    w.OPERATOR,
    eq.EQUIPMENT_ID,
    eq.EQUIPMENT_CODE,
    eq.EQUIPMENT_NAME,
    eq.EQUIPMENT_TYPE,
    eq.MANUFACTURER,
    eq.MODEL,
    eq.SERIAL_NUMBER,
    eq.INSTALL_DATE,
    eq.LAST_MAINTENANCE_DATE,
    eq.STATUS AS EQUIPMENT_STATUS,
    eq.FAILURE_DATE,
    DATEDIFF('day', eq.INSTALL_DATE, CURRENT_DATE()) AS DAYS_SINCE_INSTALL,
    CASE WHEN eq.STATUS = 'FAILED' THEN TRUE ELSE FALSE END AS IS_FAILED
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELLS w
JOIN OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_EDGE e 
    ON w.WELL_ID = e.SOURCE_NODE_ID AND e.EDGE_TYPE = 'HAS_EQUIPMENT'
JOIN OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_EQUIPMENT eq 
    ON e.TARGET_NODE_ID = eq.EQUIPMENT_ID;

-- Layer 3: Field Production View
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_FIELD_PRODUCTION 
COMMENT = 'Ontology View: Field-level production aggregation'
AS
SELECT 
    f.FIELD_ID,
    f.FIELD_CODE,
    f.FIELD_NAME,
    f.BASIN,
    f.REGION,
    wp.PERIOD_DATE,
    wp.PRODUCTION_MONTH,
    wp.PRODUCTION_QUARTER,
    wp.PRODUCTION_YEAR,
    COUNT(DISTINCT wp.WELL_ID) AS WELL_COUNT,
    SUM(wp.OIL_VOLUME_BBL) AS TOTAL_OIL_BBL,
    SUM(wp.GAS_VOLUME_MCF) AS TOTAL_GAS_MCF,
    SUM(wp.WATER_VOLUME_BBL) AS TOTAL_WATER_BBL,
    SUM(wp.DAYS_ON_PRODUCTION) AS TOTAL_DAYS_ON_PRODUCTION,
    SUM(wp.DOWNTIME_HOURS) AS TOTAL_DOWNTIME_HOURS,
    AVG(wp.UPTIME_PCT) AS AVG_UPTIME_PCT
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_FIELDS f
JOIN OG_ONTOLOGY_DEMO.PHYSICAL_LAYER.KG_EDGE e 
    ON f.FIELD_ID = e.TARGET_NODE_ID AND e.EDGE_TYPE = 'PART_OF_FIELD'
JOIN OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_PRODUCTION wp 
    ON e.SOURCE_NODE_ID = wp.WELL_ID
GROUP BY 
    f.FIELD_ID, f.FIELD_CODE, f.FIELD_NAME, f.BASIN, f.REGION,
    wp.PERIOD_DATE, wp.PRODUCTION_MONTH, wp.PRODUCTION_QUARTER, wp.PRODUCTION_YEAR;

-- Layer 3: Production Decline Analysis View
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_PRODUCTION_TREND 
COMMENT = 'Ontology View: Month-over-month production trends'
AS
SELECT 
    wp.WELL_ID,
    wp.API_NUMBER,
    wp.WELL_NAME,
    wp.OPERATOR,
    wp.PERIOD_DATE,
    wp.OIL_VOLUME_BBL,
    wp.GAS_VOLUME_MCF,
    LAG(wp.OIL_VOLUME_BBL) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE) AS PREV_MONTH_OIL,
    LAG(wp.GAS_VOLUME_MCF) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE) AS PREV_MONTH_GAS,
    wp.OIL_VOLUME_BBL - LAG(wp.OIL_VOLUME_BBL) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE) AS OIL_CHANGE_BBL,
    wp.GAS_VOLUME_MCF - LAG(wp.GAS_VOLUME_MCF) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE) AS GAS_CHANGE_MCF,
    CASE 
        WHEN LAG(wp.OIL_VOLUME_BBL) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE) > 0 
        THEN ROUND(((wp.OIL_VOLUME_BBL - LAG(wp.OIL_VOLUME_BBL) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE)) / 
              LAG(wp.OIL_VOLUME_BBL) OVER (PARTITION BY wp.WELL_ID ORDER BY wp.PERIOD_DATE)) * 100, 2)
        ELSE NULL 
    END AS OIL_CHANGE_PCT
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_PRODUCTION wp;

-- Layer 3: Shut-in Wells View
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_SHUT_IN_WELLS 
COMMENT = 'Ontology View: Currently shut-in wells'
AS
SELECT 
    w.WELL_ID,
    w.API_NUMBER,
    w.WELL_NAME,
    w.WELL_STATUS,
    w.WELL_TYPE,
    w.OPERATOR,
    w.COMPLETION_DATE,
    wf.FIELD_NAME,
    wf.BASIN,
    wf.REGION
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELLS w
LEFT JOIN OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_FIELD wf ON w.WELL_ID = wf.WELL_ID
WHERE w.WELL_STATUS = 'SHUT_IN';

-- Layer 3: Monthly Well Ranking View
CREATE OR REPLACE VIEW OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_MONTHLY_WELL_RANKING 
COMMENT = 'Ontology View: Monthly well production ranking'
AS
SELECT 
    wp.WELL_ID,
    wp.API_NUMBER,
    wp.WELL_NAME,
    wp.OPERATOR,
    wf.FIELD_NAME,
    wf.BASIN,
    wp.PERIOD_DATE,
    wp.PRODUCTION_MONTH,
    wp.OIL_VOLUME_BBL,
    wp.GAS_VOLUME_MCF,
    wp.WATER_VOLUME_BBL,
    wp.UPTIME_PCT,
    RANK() OVER (PARTITION BY wp.PRODUCTION_MONTH ORDER BY wp.OIL_VOLUME_BBL DESC) AS OIL_RANK,
    RANK() OVER (PARTITION BY wp.PRODUCTION_MONTH ORDER BY wp.GAS_VOLUME_MCF DESC) AS GAS_RANK
FROM OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_PRODUCTION wp
LEFT JOIN OG_ONTOLOGY_DEMO.ONTOLOGY_VIEWS.V_WELL_FIELD wf ON wp.WELL_ID = wf.WELL_ID;
